# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-config
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     envFrom:
#     - configMapRef:
#         name: narendra.shop
kind: Pod
apiVersion: v1
metadata:
  name: pod-conig
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: narendra.shop  
        