# kind: Pod
# apiVersion: v1
# metadata:
#   name: secret-config
# spec:
#   containers:
#   - name: nginx
#     image: nginx 
#     envFrom:
#     - secretRef:
#         name: pod-secret 
kind: Pod
apiVersion: v1
metadata:
  name: secret-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-config  