# kind: Pod
# apiVersion: v1
# metadata: 
#   name: nginx
#   labels:
#     name: nginx-test
#     project: expense
#     component: frontend
#     environment: dev
# spec:
#   containers:
#   - name: nginx
#     image: nginx

kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    name: nginx-test
    project: expense
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx 
        