# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx
# spec:
#   selector:
#     name: nginx-test
#     project: expense
#     component: frontend
#     environment: dev
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80 
kind: Service
apiVersion: v1
metadata:
  name: nginx 
spec:
  selector:
    name: nginx-test
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8082    